### ISSUE TITLE
drawing target

### ISSUE THREAD

**Issue by mfkl** [RancidMilkGames/Godot-VLC#1]
Hi there,

We are interested in supporting Godot, just lacking manpower right now. I see that you are using HWND for the drawing target. You may find https://github.com/videolan/libvlcsharp/blob/master/samples/LibVLCSharp.CustomRendering.Direct3D11/Program.cs interesting (the Unity integration uses these libvlc APIs, from C++ though).
Feel free to come say hi on our discord. Cheers!

**Comment by RancidMilkGames** [comment]
Neat! C++ Might be a better integration for Godot anyway, as it would be able to be incorporated with a standard Godot build, as opposed to needing to be the mono version. I'll for sure drop by the discord. Thanks!

**Comment by mfkl** [comment]
👍
