### ISSUE TITLE
How can I display the progress bar and other UI elements over the video during playback?

### ISSUE THREAD

**Issue by hongfeiyucode** [RancidMilkGames/Godot-VLC#3]
I’m a bit confused. Could you please help me out?

**Comment by RancidMilkGames** [comment]
> I’m a bit confused. Could you please help me out?

Hey, I believe how I rendered it you can't. You might be able to make a transparent window ontop with controls. Or look at other rendering methods. I shared this project to save others time, but figured there were better approaches that don't involve a GPL (though lesser) license to play video besides Vorbis in godot. Sorry about that. Maybe look around for some implementation of AV1 or something (other open video format) for godot?

**Comment by hongfeiyucode** [comment]
Thank you very much for your reply! be deeply grateful!

**Comment by RancidMilkGames** [comment]
> Thank you very much for your reply! be deeply grateful!

You bet!

**Comment by matjazPrijatelj** [comment]
I've managed to change your code and render vlc into TextureRect so I can layer it.

**Comment by RancidMilkGames** [comment]
> I've managed to change your code and render vlc into TextureRect so I can layer it.

Oh, that's awesome! Feel free to make a pull request or otherwise share a link I can put in the README

**Comment by hongfeiyucode** [comment]
> I've managed to change your code and render vlc into TextureRect so I can layer it.

Such a great job! I can't wait to appreciate your code!

**Comment by hongfeiyucode** [comment]
> I've managed to change your code and render vlc into TextureRect so I can layer it.

Such a great job! I can't wait to appreciate your code!

**Comment by matjazPrijatelj** [comment]
Sorry I didn't have time to make a PR but I can give you the basic code which I've adjusted:

In the editor only TextureRect assigned is needed, I've reused VidPath and Play button and removed all other elements:

`using System;
using System.Runtime.InteropServices;
using Godot;
using LibVLCSharp.Shared;

namespace libVLCsolution.Scripts
{
  public partial class App : Node
  {
    private LibVLC libVLC;
    private MediaPlayer mediaPlayer;
    private Media media;

    private ImageTexture videoTexture;
    private byte[] videoBuffer;
    private GCHandle videoBufferHandle;
    private int videoWidth;
    private int videoHeight;

    private Image image;

    [Export] private LineEdit VidPathEdit;
    [Export] private TextureRect videoDisplay;

    private bool isVideoPlaying = false;

    public override void _Ready()
    {
      base._Ready();

      Core.Initialize();

      string[] vlcOptions = { };
      libVLC = new LibVLC(vlcOptions);

      mediaPlayer = new MediaPlayer(libVLC);
      mediaPlayer.EnableHardwareDecoding = true;

      videoTexture = new ImageTexture();
      image = new Image();

      mediaPlayer.SetVideoFormatCallbacks(VideoFormat, CleanupVideo);
      mediaPlayer.SetVideoCallbacks(LockVideo, UnlockVideo, DisplayVideo);
    }

    private void MediaStateChangedHandler(object o, MediaStateChangedEventArgs mediaState)
    {
      GD.Print($"State: {mediaState.State}");
      if (mediaState.State == VLCState.Ended)
      {
        GD.Print("Video ended");
        FreeMedia();
      }
    }

    public void StartVideo()
    {
      string playPath = VidPathEdit.Text.Replace("\\", "\\\\");

      if (playPath.StartsWith("http")) { }
      else if (!FileAccess.FileExists(playPath))
      {
        GD.PrintErr("Video file not found: ", playPath);
        return;
      }

      mediaPlayer?.Stop();
      FreeMedia();

      try
      {
        media = new Media(libVLC, new Uri(playPath));
        media.StateChanged += MediaStateChangedHandler;
        mediaPlayer.Play(media);
        isVideoPlaying = true;
      }
      catch (Exception ex)
      {
        GD.PrintErr("Error starting video: ", ex.Message);
      }
    }

    private uint VideoFormat(ref IntPtr opaque, IntPtr chroma, ref uint width, ref uint height, ref uint pitches, ref uint lines)
    {
      string chromaFormat = "RGBA";
      byte[] chromaBytes = System.Text.Encoding.ASCII.GetBytes(chromaFormat);
      Marshal.Copy(chromaBytes, 0, chroma, chromaBytes.Length);

      videoWidth = (int)width;
      videoHeight = (int)height;

      pitches = (uint)(videoWidth * 4);
      lines = (uint)videoHeight;

      if (videoBuffer == null)
      {
        videoBuffer = new byte[videoWidth * videoHeight * 4]; // RGBA buffer
        videoBufferHandle = GCHandle.Alloc(videoBuffer, GCHandleType.Pinned);
      }

      image.SetData(videoWidth, videoHeight, false, Image.Format.Rgba8, videoBuffer);

      if (videoTexture != null)
      {
        videoTexture.Dispose();
      }

      videoTexture = ImageTexture.CreateFromImage(image);
      CallDeferred(nameof(UpdateTexture), videoTexture);

      return 1;
    }

    private void UpdateTexture(ImageTexture texture)
    {
      if (videoDisplay != null)
      {
        videoDisplay.Texture = texture;
      }
    }

    private void CleanupVideo(ref IntPtr opaque)
    {
      if (videoBufferHandle.IsAllocated)
      {
        videoBufferHandle.Free();
      }

      videoBuffer = null;
      videoTexture?.Dispose();
      videoTexture = null;
    }

    private IntPtr LockVideo(IntPtr opaque, IntPtr planes)
    {
      Marshal.WriteIntPtr(planes, videoBufferHandle.AddrOfPinnedObject());
      return IntPtr.Zero;
    }

    private void UnlockVideo(IntPtr opaque, IntPtr picture, IntPtr planes) { }

    private float lastUpdateTime = 0f;
    private const float updateInterval = 1f / 30f; // 30 fps

    private void DisplayVideo(IntPtr opaque, IntPtr picture)
    {
      float currentTime = Time.GetTicksMsec() / 1000f;
      if (currentTime - lastUpdateTime >= updateInterval)
      {
        lastUpdateTime = currentTime;
        CallDeferred(nameof(UpdateDisplayVideo), videoTexture);
      }
    }

    private void UpdateDisplayVideo(ImageTexture texture)
    {
      if (videoTexture != null && videoBuffer != null)
      {
        image.SetData(videoWidth, videoHeight, false, Image.Format.Rgba8, videoBuffer);
        videoTexture.Update(image);
      }
    }

    private void FreeMedia()
    {
      if (media != null)
      {
        media.StateChanged -= MediaStateChangedHandler;
        media.Dispose();
        media = null;
      }
    }

    public override void _ExitTree()
    {
      FreeMedia();
      mediaPlayer?.Dispose();
      libVLC?.Dispose();

      if (videoBufferHandle.IsAllocated)
      {
        videoBufferHandle.Free();
      }
      videoTexture?.Dispose();
    }
  }
}`

**Comment by RancidMilkGames** [comment]
> Sorry I didn't have time to make a PR but I can give you the basic code which I've adjusted:
> 
> In the editor only TextureRect assigned is needed, I've reused VidPath and Play button and removed all other elements:
> 
> `using System;
> using System.Runtime.InteropServices;
> using Godot;
> using LibVLCSharp.Shared;
> 
> namespace libVLCsolution.Scripts
> {
>   public partial class App : Node
>   {
>     private LibVLC libVLC;
>     private MediaPlayer mediaPlayer;
>     private Media media;
> 
>     private ImageTexture videoTexture;
>     private byte[] videoBuffer;
>     private GCHandle videoBufferHandle;
>     private int videoWidth;
>     private int videoHeight;
> 
>     private Image image;
> 
>     [Export] private LineEdit VidPathEdit;
>     [Export] private TextureRect videoDisplay;
> 
>     private bool isVideoPlaying = false;
> 
>     public override void _Ready()
>     {
>       base._Ready();
> 
>       Core.Initialize();
> 
>       string[] vlcOptions = { };
>       libVLC = new LibVLC(vlcOptions);
> 
>       mediaPlayer = new MediaPlayer(libVLC);
>       mediaPlayer.EnableHardwareDecoding = true;
> 
>       videoTexture = new ImageTexture();
>       image = new Image();
> 
>       mediaPlayer.SetVideoFormatCallbacks(VideoFormat, CleanupVideo);
>       mediaPlayer.SetVideoCallbacks(LockVideo, UnlockVideo, DisplayVideo);
>     }
> 
>     private void MediaStateChangedHandler(object o, MediaStateChangedEventArgs mediaState)
>     {
>       GD.Print($"State: {mediaState.State}");
>       if (mediaState.State == VLCState.Ended)
>       {
>         GD.Print("Video ended");
>         FreeMedia();
>       }
>     }
> 
>     public void StartVideo()
>     {
>       string playPath = VidPathEdit.Text.Replace("\\", "\\\\");
> 
>       if (playPath.StartsWith("http")) { }
>       else if (!FileAccess.FileExists(playPath))
>       {
>         GD.PrintErr("Video file not found: ", playPath);
>         return;
>       }
> 
>       mediaPlayer?.Stop();
>       FreeMedia();
> 
>       try
>       {
>         media = new Media(libVLC, new Uri(playPath));
>         media.StateChanged += MediaStateChangedHandler;
>         mediaPlayer.Play(media);
>         isVideoPlaying = true;
>       }
>       catch (Exception ex)
>       {
>         GD.PrintErr("Error starting video: ", ex.Message);
>       }
>     }
> 
>     private uint VideoFormat(ref IntPtr opaque, IntPtr chroma, ref uint width, ref uint height, ref uint pitches, ref uint lines)
>     {
>       string chromaFormat = "RGBA";
>       byte[] chromaBytes = System.Text.Encoding.ASCII.GetBytes(chromaFormat);
>       Marshal.Copy(chromaBytes, 0, chroma, chromaBytes.Length);
> 
>       videoWidth = (int)width;
>       videoHeight = (int)height;
> 
>       pitches = (uint)(videoWidth * 4);
>       lines = (uint)videoHeight;
> 
>       if (videoBuffer == null)
>       {
>         videoBuffer = new byte[videoWidth * videoHeight * 4]; // RGBA buffer
>         videoBufferHandle = GCHandle.Alloc(videoBuffer, GCHandleType.Pinned);
>       }
> 
>       image.SetData(videoWidth, videoHeight, false, Image.Format.Rgba8, videoBuffer);
> 
>       if (videoTexture != null)
>       {
>         videoTexture.Dispose();
>       }
> 
>       videoTexture = ImageTexture.CreateFromImage(image);
>       CallDeferred(nameof(UpdateTexture), videoTexture);
> 
>       return 1;
>     }
> 
>     private void UpdateTexture(ImageTexture texture)
>     {
>       if (videoDisplay != null)
>       {
>         videoDisplay.Texture = texture;
>       }
>     }
> 
>     private void CleanupVideo(ref IntPtr opaque)
>     {
>       if (videoBufferHandle.IsAllocated)
>       {
>         videoBufferHandle.Free();
>       }
> 
>       videoBuffer = null;
>       videoTexture?.Dispose();
>       videoTexture = null;
>     }
> 
>     private IntPtr LockVideo(IntPtr opaque, IntPtr planes)
>     {
>       Marshal.WriteIntPtr(planes, videoBufferHandle.AddrOfPinnedObject());
>       return IntPtr.Zero;
>     }
> 
>     private void UnlockVideo(IntPtr opaque, IntPtr picture, IntPtr planes) { }
> 
>     private float lastUpdateTime = 0f;
>     private const float updateInterval = 1f / 30f; // 30 fps
> 
>     private void DisplayVideo(IntPtr opaque, IntPtr picture)
>     {
>       float currentTime = Time.GetTicksMsec() / 1000f;
>       if (currentTime - lastUpdateTime >= updateInterval)
>       {
>         lastUpdateTime = currentTime;
>         CallDeferred(nameof(UpdateDisplayVideo), videoTexture);
>       }
>     }
> 
>     private void UpdateDisplayVideo(ImageTexture texture)
>     {
>       if (videoTexture != null && videoBuffer != null)
>       {
>         image.SetData(videoWidth, videoHeight, false, Image.Format.Rgba8, videoBuffer);
>         videoTexture.Update(image);
>       }
>     }
> 
>     private void FreeMedia()
>     {
>       if (media != null)
>       {
>         media.StateChanged -= MediaStateChangedHandler;
>         media.Dispose();
>         media = null;
>       }
>     }
> 
>     public override void _ExitTree()
>     {
>       FreeMedia();
>       mediaPlayer?.Dispose();
>       libVLC?.Dispose();
> 
>       if (videoBufferHandle.IsAllocated)
>       {
>         videoBufferHandle.Free();
>       }
>       videoTexture?.Dispose();
>     }
>   }
> }`

Hey, thanks! I'll update the code with a credit mention if that's OK with you?

**Comment by matjazPrijatelj** [comment]
Yes no problem.
